# Site settings
title: One More Bottle
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  So this is my blog, I’ll be focusing on nail type things with maybe a dash of reviews for cosmetics. 
  I don’t really do hauls because this is a hobby not a job so... lack of money does that. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

colors:  #in hex code if not noted else
  primary: "#7769ac"
  primary_rgb: "113,105,172"
  secondary: "#384452"
  link: "#7769ac"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
